### ISSUE TITLE
Bug in Support Generation for large and complex stl parts

### ISSUE THREAD

**Issue by Vipul-M-Rawal** [drlukeparry/pyslm#46]
Hi, I am facing issues generating block supports for the given parts. I am getting almost the same problems for many parts. To solve the issues I made some changes in the parameters also, but still the issue persists.
I am attaching the stl file and the code below:

code :
[Code.txt](https://github.com/user-attachments/files/16690854/Code.txt)

I am getting the given errors:

**ERROR:root:Support generation failed: Input must be >= 1-d.**

WARNING: Traceback (most recent call last):
  File "c:\Users\vipul.k\Music\VolumeGen\Volume.py", line 98, in <module>
    supportBlockRegions = supportGenerator.identifySupportRegions(myPart, OVERHANG_ANGLE, True)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\gridBlockSupport.py", line 1936, in identifySupportRegions
    supportBlocks = super().identifySupportRegions(part, overhangAngle, findSelfIntersectingSupport)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\support.py", line 851, in identifySupportRegions
    heightMap, heightMapUpper, heightMapLower = self._identifySelfIntersectionHeightMap(subregion, offsetPoly, cutMeshUpper, bbox)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\support.py", line 624, in _identifySelfIntersectionHeightMap
    lowerImg = render.projectHeightMap(cutMesh, self.rayProjectionResolution, True, bboxCpy)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\render.py", line 188, in projectHeightMap
    c.show(visible=True)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\canvas.py", line 435, in show
    self._backend._vispy_set_visible(visible)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\backends\_qt.py", line 465, in _vispy_set_visible
    self.showNormal()
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\backends\_qt.py", line 626, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\backends\_qt.py", line 626, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\backends\_qt.py", line 928, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\util\event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\util\event.py", line 469, in _invoke_callback
    cb(event)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\render.py", line 175, in on_draw
    self.program.draw('triangles', self.filled_buf)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\program.py", line 543, in draw
    canvas.context.flush_commands()
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 584, in flush
    self._shared.flush(parser)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 506, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 824, in parse
    self._parse(command)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 800, in _parse
    ob.set_framebuffer(*args)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 1758, in set_framebuffer
    self._validate()
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 1823, in _validate
    raise RuntimeError(_bad_map.get(res, 'Unknown framebuffer error: %r.'
RuntimeError: Target not equal to GL_FRAMEBUFFER
WARNING:vispy:Traceback (most recent call last):
  File "c:\Users\vipul.k\Music\VolumeGen\Volume.py", line 98, in <module>
    supportBlockRegions = supportGenerator.identifySupportRegions(myPart, OVERHANG_ANGLE, True)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\gridBlockSupport.py", line 1936, in identifySupportRegions
    supportBlocks = super().identifySupportRegions(part, overhangAngle, findSelfIntersectingSupport)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\support.py", line 851, in identifySupportRegions
    heightMap, heightMapUpper, heightMapLower = self._identifySelfIntersectionHeightMap(subregion, offsetPoly, cutMeshUpper, bbox)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\support.py", line 624, in _identifySelfIntersectionHeightMap
    lowerImg = render.projectHeightMap(cutMesh, self.rayProjectionResolution, True, bboxCpy)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\render.py", line 188, in projectHeightMap
    c.show(visible=True)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\canvas.py", line 435, in show
    self._backend._vispy_set_visible(visible)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\backends\_qt.py", line 465, in _vispy_set_visible
    self.showNormal()
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\backends\_qt.py", line 626, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\backends\_qt.py", line 626, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\app\backends\_qt.py", line 928, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\util\event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\util\event.py", line 469, in _invoke_callback
    cb(event)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyslm\support\render.py", line 175, in on_draw
    self.program.draw('triangles', self.filled_buf)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\program.py", line 543, in draw
    canvas.context.flush_commands()
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 584, in flush
    self._shared.flush(parser)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 506, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 824, in parse
    self._parse(command)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 800, in _parse
    ob.set_framebuffer(*args)
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 1758, in set_framebuffer
    self._validate()
  File "C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\vispy\gloo\glir.py", line 1823, in _validate
    raise RuntimeError(_bad_map.get(res, 'Unknown framebuffer error: %r.'
RuntimeError: Target not equal to GL_FRAMEBUFFER
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x22ccc1ee4e0>> for DrawEvent
ERROR:vispy:Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x22ccc1ee4e0>> for DrawEvent

INFO:root:Time taken for support geometry creation: 46.22 seconds
C:\Users\vipul.k\AppData\Roaming\Python\Python312\site-packages\pyglet\libs\win32\__init__.py:318: UserWarning: Could not set COM MTA mode. Unexpected behavior may occur.
  warnings.warn("Could not set COM MTA mode. Unexpected behavior may occur.")
  
  
[Structure-pack_200 mm.zip](https://github.com/user-attachments/files/16690801/Structure-pack_200.mm.zip)

**Comment by drlukeparry** [comment]
the error appears related to the vispy module, which is using the _pyglet_ backend, which I have observed to create some problems in the past depending on the system/platform used. Additionally, the functionality depends on having reasonably modern openGL graphics drivers that support floating-point depth framebuffers, otherwise the raytracing approach method breaks down when attempting to create supports.  I imagine under certain virtualisation / cloud platforms this could be problematic. 

 I would suggest to install PyQt5 / PyQt6 and set the corresponding backend for vispy to use this and see if this fixes the problem you are encountering.

**Comment by QuentinoPersonal66** [comment]
Hi Luke,
I faced the same problem even though I have PyQt5 and vispy installed.
versions are
vispy                     0.14.3
pyqt5                     5.15.11

I am using windows 11. 
which version are you using ?

**Comment by drlukeparry** [comment]
@QuentinoPersonal66 - can you provide any information on your graphics card (+driver) - my suspicion is that some Graphics Cards don't support floating point framebuffers and is why the error is raised by Vispy. 

This happened to me previously on an older system (Ubuntu OS with integrated Intel GPU), which only provided RGB8 format and created a variety of issues obtaining the projection map.

**Comment by QuentinoPersonal66** [comment]
@drlukeparry my graphic card is intel(R) graphics. 
driver version is 32.0.101.5972.

**Comment by QuentinoPersonal66** [comment]
I found out that decreasing the rayprojection resolution can help

**Comment by drlukeparry** [comment]
@QuentinoPersonal66 - that's helpful, thank you for reporting that. Likely the issues is the framebuffer size is being exceeded at the ray projection resolution chosen for a large support area. Some GPUs and Graphics Drivers have a restriction of the framebuffer size (in pixels). The default ray projection resolution is a tradeoff between accuracy and detail for parts with not a large overhang size.

**Comment by drlukeparry** [comment]
Will be resolved in 0.7.0 with new occlusion based block support generation
